# BUILD
FROM node:14-alpine AS build_stage

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build-prod

# PRODUÇÃO
FROM nginxinc/nginx-unprivileged

COPY --from=build_stage /usr/src/app/dist/k8s-ocp-view /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
